### ISSUE TITLE
Map popup box fonts too small

### ISSUE THREAD

**Issue by spjika** [openoakland/EarlyOakland#19]
Given lots of grandparents help find these services we need to bump up the text box size and the font size in the popup on the map page.

**Comment by spjika** [comment]
Tarik fixed the sizes, but there's a colon that shows up on the Times and School Hours fields, someone able to clear that up? @jcmorrow ?

**Comment by jcmorrow** [comment]
Is it showing up consistently in the same place on each popup? I noticed that most of them had some kind of error, but it looked like it was different for each popup. Because of that I suspect it has more to do with a JSON parsing error or maybe just some missing data than it does with the html. I didn’t have time to poke around in the JSON parsing last night, but I’d be happy to investigate this evening.

Josh

**Comment by spjika** [comment]
Seems fairly consistent, actually on another screen it seems more like it's
wrapping the colon from the title of each row, not the actual data, to the
colon for Time: shows up on the next line down. I know @maxogden built the
popup to work well on mobile so it's smallish overall, we may need to look
at a more repsonsive approach to the popup?

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by jcmorrow** [comment]
Ah, yeah. It seemed more chaotic last night, but I see it now. I bet that is in the HTML. I’ll take a break from leaflet.js land and do some digging right now.

Josh

**Comment by jcmorrow** [comment]
It’s fixed and the pull request is sent!

Josh

**Comment by fsargent** [comment]
looks fixed by #23  #22  #21  #20
