### ISSUE TITLE
color code map markers

### ISSUE THREAD

**Issue by max-mapper** [openoakland/EarlyOakland#4]
there are colors on the filter checkboxes, we should use those colors for the map markers

**Comment by sahlhoff** [comment]
Hey, the filters currently intersect each other.  Is there any presidence of a filter over the other?

**Comment by max-mapper** [comment]
Good question... I hadn't considered that. Maybe we can recolor the first section (yellows) into 4 separate colors and base the marker color on that

Spike, what do you think?

**Comment by spjika** [comment]
there is yeah, just noticed it today.

Max- colors=yes. More useful than filters.

I posted the priority in the Issues earlier:
https://github.com/openoakland/EarlyOakland/issues/3

****Filters should be additive, not exclusive within each set - use OR:
So if you select 3-5 Years alone, those sites will be visible and will be
searched. If you then add 3-8 Years it will use an OR to show/search all
sites with a YES in the 3-5 and in the 3-8 field. There are no exclusions
if a site does one- it can do the other too so both need to show.

Also with the TIMES - these should be additive with the ages- so if 3-5 is
ticked and shows, if you select a FULL DAY then this should show sites with
3-5 as YES AND also with FULL DAY as YES. But withIN the TIMES and the AGES
they need to operate as ORs- to adding 1/2 Day to the FULL DAY filter would
show all sites with both options.

Is this clear enough? The premise is that a user will want to see what
sites exist in total when first getting to the site, then perhaps narrow it
down by their kids age, and then many by the time of day they need. If this
creates problems with the js in the template we should talk about the
defaults to make it clearer for typical parent use cases.
thanks yall!

---

BUT- we had discussed this approach, and decided that something cleaner was
needed, so that got built- but it does need to highlight the types of
facilities- even if they don't get searched specifically- parents want a
place, they don't likely know or care about the difference. But if we do
have type filters, these take precedence.

With age ranges- it's more obvious if they are combined yeah, given a place
can handle multiple ranges, clicking more than one shows ALL those results.
Then with availability- these are the third layer of importance, again some
sites do all options so they should be combining results, not excluding.

Spike

**Comment by max-mapper** [comment]
maybe something like a horizontal slider for ages? (pardon the crude ASCII)

``` js
Ages
| ====|| - - | - - - |
 0      3     5     8
```

**Comment by spjika** [comment]
There's some sense in making the age thing more logical yeah- part of the
issue to understand is this: some sites do multiple of the ranges given, so
3-5 and 3-8. I don't think it would happen where parents would look for a
place that does "3-5" AND "3-8" as they are somewhat arbitrary ranges the
system offers. But, I'm not sure if it's an advantage to have ranges to
make it easier for parents with multiple kids to find a place that does
both?

It would be a fair thing to recode the age data fields so we can do a
slider or number entry box to say tell us how old your kid is.  User
testing may reveal that parents strangely do want those arbitrary ranges
though- let's float this idea to the city team first ok?

Spike

**Comment by sahlhoff** [comment]
Glancing over the data again it appears that the type of program has a connection with the age group:

Head Start => 3-5 yrs

Head Start Family Child Care => 3-5 yrs

Early Head Start => Prenatal to 3 years

OUSD => is a wildcard

OUSD is almost half of the data.  My thoughts would be to only have a slider available if OUSD is selected and have the color codes divided by types of program.
